version: "3"
services:
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - "./config/nginx/twue.conf:/etc/nginx/conf.d/twue.dev"
      - ".:/var/www"
  php:
    image: php:7.2-fpm
    volumes:
      - ".:/var/www"
